name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.8.0

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI and EAS
        run: npm install -g expo-cli eas-cli

      - name: Build APK with EAS
        run: eas build --platform android --profile release --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
